repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(mlx_arsenal|tests)/
      - id: ruff-format
        files: ^(mlx_arsenal|tests)/
